[workspace]

members = [
    "copernica-broker",
    "copernica-services",
    "copernica-links",
    "copernica-common",
    "copernica-tests",
    "copernica-clients",
    "copernica-protocols",
]
exclude = [
    "copernica-sentinel",
]
